spring.application.name=ExpenseTracker

spring.datasource.url=jdbc:postgresql://dpg-d2m1gk75r7bs73e7imn0-a.oregon-postgres.render.com:5432/drone_tracker_d4tz
spring.datasource.username=akanksha_user
spring.datasource.password=dQTU7RwScYDWCotXi27m4jiiTz0NbYCF
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
